### ISSUE TITLE
The problem of datasets

### ISSUE THREAD

**Issue by XiaoHong0-0** [TiantianZhu110/BioPRO#2]
Could you please tell me how to get the datasets and how to put them in the correct folder path?

**Comment by TiantianZhu110** [comment]
1. Prepare the original dataset (e.g., medmentions_train.txt, medmentions_dev.txt, , medmentions_test.txt) and KB (e.g., umls2017aa_reference_ont.txt, MRSTY.RRF, SRDEF). 
2. Use the 'data_process.py' to generate intermediate processing files (e.g., medmention.train, medmention.dev, medmention.test) and each instance has the format: '{"doc_id": "", "mention_name": "", "mention_context": "", "cui_id": "", "cui_name": [], "cui_type": []}'.
3. Prepare the intermediate processing files (e.g., medmention.train, medmention.dev) and the SAPBERT top 10 predictions (e.g., predictions_train_sapbert_top10.json, predictions_dev_sapbert_top10.json), and use the 'data_process.py' to generate the final training prompt data.
4. Prepare the intermediate processing files (e.g., medmention.test) and the SAPBERT top 10 predictions (e.g., predictions_test_sapbert_top10.json), and use the 'data_process.py' to generate the final test prompt data.

**Comment by NargesFarrokhshad** [comment]
Hello Tiantian, Thank you for sharing your work, Could you tell me how you you create medmention_train.txt, and predictions_train_sapbert_top10.json file? Here is my email 
narges.farrokhshad@gmail.com
