### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by Stubborn-z** [TiantianZhu110/BioPRO#3]
Hello and thanks for sharing this great project. 
I am very interested in your work. Could you please tell me how to get the datasets umls2017aa_reference_ont.txt,MRSTY.RRF and SRDEF?

**Comment by TiantianZhu110** [comment]
The umls2017aa_reference_ont.txt,MRSTY.RRF and SRDEF datasets can be downloaded from the [UMLS official website](https://www.nlm.nih.gov/research/umls/licensedcontent/umlsknowledgesources.html) (2017AA full version).

**Comment by Stubborn-z** [comment]
thank you very much！


1639682361
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TiantianZhu110/BioPRO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月26日(星期三) 晚上8:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TiantianZhu110/BioPRO] Datasets (Issue #3)





 
The umls2017aa_reference_ont.txt,MRSTY.RRF and SRDEF datasets can be downloaded from the UMLS official website (2017AA full version).

**Comment by Stubborn-z** [comment]
> The umls2017aa_reference_ont.txt,MRSTY.RRF and SRDEF datasets can be downloaded from the [UMLS official website](https://www.nlm.nih.gov/research/umls/licensedcontent/umlsknowledgesources.html) (2017AA full version).

Sorry to bother you again, I downloaded the umls-2017AA-full dataset, but did not find the umls2017aa_reference_ont.txt you mentioned, may I ask how I get this?

**Comment by Stubborn-z** [comment]
Sorry to bother you again, I downloaded the umls-2017AA-full dataset, but did not find the umls2017aa_reference_ont.txt you mentioned, may I ask how I get this?&nbsp;I would appreciate it if you could tell me.
&nbsp;


1639682361
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TiantianZhu110/BioPRO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月26日(星期三) 晚上8:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TiantianZhu110/BioPRO] Datasets (Issue #3)





 
The umls2017aa_reference_ont.txt,MRSTY.RRF and SRDEF datasets can be downloaded from the UMLS official website (2017AA full version).

**Comment by TiantianZhu110** [comment]
Yes, please leave your email here.

**Comment by Stubborn-z** [comment]
***@***.***
Thanks!


1639682361
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TiantianZhu110/BioPRO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月2日(星期三) 中午11:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TiantianZhu110/BioPRO] Datasets (Issue #3)





 
Yes, please leave your email here.

**Comment by TiantianZhu110** [comment]
I can't see your email address.

**Comment by Stubborn-z** [comment]
> I can't see your email address.
I'm sorry.
1639682361@qq.com
Thank you very much

**Comment by Stubborn-z** [comment]
I'm sorry.
***@***.***
Thank you very much


1639682361
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TiantianZhu110/BioPRO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月2日(星期三) 晚上7:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TiantianZhu110/BioPRO] Datasets (Issue #3)





 
I can't see your email address.

**Comment by Stubborn-z** [comment]
> I can't see your email address.

I'm sorry.
 That's my email 1639682361@qq.com
Thank you very much

**Comment by mk2x15** [comment]
Hi, could you please also tell me how to get all the data files? Thanks! My email is mk2x15@gmail.com
