### ISSUE TITLE
Dataset problem

### ISSUE THREAD

**Issue by mk2x15** [TiantianZhu110/BioPRO#4]
Hi, could you please also tell me how to get all the data files? Thanks! My email is mk2x15@gmail.com

**Comment by TiantianZhu110** [comment]
Okay, the data files have been sent.

**Comment by mk2x15** [comment]
Thanks a lot! May I know how to process the NCBI dataset as well?

**Comment by TiantianZhu110** [comment]
You can download the NCBI dataset from here
<https://www.dropbox.com/s/s33fxxg23ev59ic/mel-test-data.tar.gz?dl=0>.

mk2x15 ***@***.***> 于2022年12月5日周一 14:45写道：

**Comment by mk2x15** [comment]
Thanks so much for your prompt reply! May I know how to process the NCBI files by "data_process.py"?

**Comment by TiantianZhu110** [comment]
The "data_process.py" can only pocess the MedMentions dataset. However, you can write a similar data_process code for the NCBI dataset. By the way, you can download the original NCBI dataset from [here](https://www.ncbi.nlm.nih.gov/CBBresearch/Dogan/DISEASE/), which includes the context.

**Comment by mk2x15** [comment]
Ok, but could you please release your processing codes for NCBI dataset as well? so that we could reproduce the results on this dataset. BTW, may I know where those files are? i.e. "golden_ent_file", "golden_type_file" and "type_file" for NCBI dataset. Thanks!

**Comment by ainilian** [comment]
> Thanks a lot! May I know how to process the NCBI dataset as well?

Hi, What kind dataset the author sent to you? NCBI dataset or MedMentions dataset, which one?

**Comment by TiantianZhu110** [comment]
> 

The processing codes and required data files for the NCBI dataset have been uploaded.
